apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerbackend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dockerbackend
  template:
    metadata:
      labels:
        app: dockerbackend
    spec:
      containers:
        - name: dockerbackend
          image: myapp:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000